services:
  mariadb:
    image: mariadb:10.6
    networks: [ 'mppz' ]
    volumes: [ 'mariadb_data:/var/lib/mysql' ]
    environment:
      - MARIADB_ROOT_PASSWORD=123456789
      - MARIADB_DATABASE=mppz
      - MARIADB_USER=mppz
      - MARIADB_PASSWORD=123456789
    restart: unless-stopped
  mppz-api:
    build: .
    pull_policy: build
    networks: [ 'mppz' ]
    depends_on:
      - mariadb
    restart: unless-stopped
    ports:
      - '127.0.0.1:64181:8080'

networks:
  mppz:
    driver: bridge

volumes:
  mariadb_data:
    driver: local